/*
 * GenreGrid — a style-based MIDI generator.
 * Copyright (C) 2026 Tw Dover
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version. Distributed WITHOUT ANY WARRANTY. See the GNU General Public License
 * <https://www.gnu.org/licenses/> for details.
 */
import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { SAMPLED_BASS_VOICES, BASS_SAMPLE_DIR } from './bass'
import { SAMPLED_VOICES } from './melodic'
import { normalizeLayers, type LayeredSamplerManifest } from './layeredSampler'

// These sets are generated by scripts/build_velocity_samples.py and then shipped
// as-is, so nothing at runtime would notice if a spec drifted — a note key that
// Tone can't parse, a file the manifest names but the build pruned, or (the real
// bug this caught) a whole set mapped an octave off because the source library
// names its files by written rather than sounding pitch. Validate them on disk.

// Vite rewrites import.meta.url to an http URL under jsdom, so the samples tree
// has to be found relative to the working directory — which differs depending on
// whether vitest is run from frontend/ or from the repo root.
function findSamplesDir(): string {
  const candidates = ['public/samples', 'frontend/public/samples']
  for (let dir = process.cwd(), i = 0; i < 4; i++, dir = path.dirname(dir)) {
    for (const candidate of candidates) {
      const full = path.join(dir, candidate)
      if (fs.existsSync(full)) return full
    }
  }
  throw new Error(`Could not locate public/samples from ${process.cwd()}`)
}

const SAMPLES_DIR = findSamplesDir()

const PITCH_CLASS: Record<string, number> = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 }

function noteToMidi(name: string): number | null {
  const m = /^([A-G])([#b]?)(-?\d+)$/.exec(name)
  if (!m) return null
  const offset = m[2] === '#' ? 1 : m[2] === 'b' ? -1 : 0
  return PITCH_CLASS[m[1]] + offset + (Number(m[3]) + 1) * 12
}

/** The window each set's lowest..highest sampled note must fall inside — the
 *  built span ±2 semitones. Deliberately tight: the point is that an octave
 *  slip in a spec fails here rather than in someone's ears, so any window
 *  wider than ±11 would defeat the test. Widen only alongside a spec change. */
const EXPECTED_SPAN: Record<string, [number, number]> = {
  'melodic/vibraphone': [51, 90],            // F3..E6
  'melodic/electric_piano_1': [27, 90],      // F1..E6
  'melodic/electric_piano_2': [31, 94],      // A1..Ab6
  'melodic/string_ensemble_1': [34, 88],     // C2..D6
  'melodic/drawbar_organ': [36, 96],         // C2..C7
  'melodic/accordion': [47, 79],             // B2..G5
  'melodic/acoustic_guitar_nylon': [31, 84], // G1..C6
  'bass/acoustic_bass': [22, 59],            // C1..A3
  'bass/electric_bass_finger': [23, 65],     // Db1..Eb4
  'bass/electric_bass_pick': [23, 63],       // Db1..Db4
  'bass/fretless_bass': [19, 59],            // A0..A3
}

function findManifests(): string[] {
  const out: string[] = []
  for (const group of fs.readdirSync(SAMPLES_DIR)) {
    const groupDir = path.join(SAMPLES_DIR, group)
    if (!fs.statSync(groupDir).isDirectory()) continue
    for (const inst of fs.readdirSync(groupDir)) {
      if (fs.existsSync(path.join(groupDir, inst, 'velocity.json'))) out.push(`${group}/${inst}`)
    }
  }
  return out.sort()
}

const manifests = findManifests()

function load(rel: string): LayeredSamplerManifest {
  return JSON.parse(fs.readFileSync(path.join(SAMPLES_DIR, rel, 'velocity.json'), 'utf8'))
}

describe('shipped velocity.json manifests', () => {
  it('ships every set the expectations cover, and no unexpected extras', () => {
    expect(manifests).toEqual(Object.keys(EXPECTED_SPAN).sort())
  })

  it.each(manifests)('%s — layers are usable', (rel) => {
    const manifest = load(rel)
    expect(manifest.layers.length).toBeGreaterThan(0)

    const layers = normalizeLayers({ manifest })
    // Ascending ceilings, and the loudest layer must catch velocity 1.0 or notes
    // played at full velocity would fall through to no layer at all.
    const ceilings = layers.map((l) => l.maxVelocity)
    expect(ceilings).toEqual([...ceilings].sort((a, b) => a - b))
    expect(ceilings[ceilings.length - 1]).toBe(1)

    for (const layer of layers) expect(Object.keys(layer.urls).length).toBeGreaterThan(0)
  })

  it.each(manifests)('%s — every referenced sample exists and is non-empty', (rel) => {
    const missing: string[] = []
    for (const layer of load(rel).layers) {
      for (const value of Object.values(layer.urls)) {
        for (const file of Array.isArray(value) ? value : [value]) {
          const full = path.join(SAMPLES_DIR, rel, file)
          if (!fs.existsSync(full) || fs.statSync(full).size === 0) missing.push(file)
        }
      }
    }
    expect(missing).toEqual([])
  })

  it.each(manifests)('%s — note names parse and sit in the expected octave', (rel) => {
    const midis: number[] = []
    for (const layer of load(rel).layers) {
      for (const note of Object.keys(layer.urls)) {
        const midi = noteToMidi(note)
        expect(midi, `unparseable note name ${note} in ${rel}`).not.toBeNull()
        midis.push(midi as number)
      }
    }
    const [lo, hi] = EXPECTED_SPAN[rel]
    expect(Math.min(...midis)).toBeGreaterThanOrEqual(lo)
    expect(Math.max(...midis)).toBeLessThanOrEqual(hi)
  })
})

describe('sampled-voice allowlists', () => {
  it('every sampled bass voice resolves to a set on disk', () => {
    for (const voice of SAMPLED_BASS_VOICES) {
      const dir = BASS_SAMPLE_DIR[voice] ?? voice
      expect(manifests, `bass voice ${voice} → ${dir}`).toContain(`bass/${dir}`)
    }
  })

  it('every sampled melodic voice resolves to a set on disk', () => {
    for (const voice of SAMPLED_VOICES) {
      expect(manifests, `melodic voice ${voice}`).toContain(`melodic/${voice}`)
    }
  })
})
