#!/usr/bin/env python3
# GenreGrid — a style-based MIDI generator.
# Copyright (C) 2026 Tw Dover
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version. Distributed WITHOUT ANY WARRANTY. See the GNU General Public License
# <https://www.gnu.org/licenses/> for details.
"""
Quality baseline sweep — the measurement harness for docs/roadmap-v3.md.

Unlike scripts/batch_generate.py (random seeds, library-building), this runs a
**fixed** seed set so two runs of the same code produce byte-identical results.
Every roadmap-v3 item re-runs this sweep and compares against the stored
baseline; that comparison is what "scores improve / attempts drop /
byte-identical" claims are judged on.

What it records per case (style x seed x meter):
  * the per-dimension quality scores of the attempt the search actually picked
  * how many attempts the best-of-N search burned before it went green
  * a hash of the winning attempt's note events — the byte-identical invariant

Usage (from repo root):
    python scripts/quality_baseline.py                       # sweep -> docs/quality-baseline-v3.json
    python scripts/quality_baseline.py --out /tmp/after.json
    python scripts/quality_baseline.py --compare docs/quality-baseline-v3.json
    python scripts/quality_baseline.py --suites meters --styles jazz rock
    python scripts/quality_baseline.py --compare docs/quality-baseline-v3.json --require-identical

`--compare` re-runs the sweep using the *baseline file's own* config and seeds
(so the two are always comparable) and prints per-dimension deltas plus a count
of cases whose events changed. `--require-identical` additionally exits 1 if any
event hash moved — the gated-off / 4-4-unchanged check every PR should run.

Single-threaded on purpose: the generators seed the global `random` module, so
running cases in parallel would destroy reproducibility.
"""

import argparse
import hashlib
import json
import platform
import subprocess
import sys
import time
from pathlib import Path

# ── path setup ────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
sys.path.insert(0, str(BACKEND_DIR))

from app.core.arrangement import _part_seed                       # noqa: E402
from app.models.schemas import GenerateRequest                    # noqa: E402
from app.services.generation import (                             # noqa: E402
    _all_green, _blend_styles, _MAX_QUALITY_ATTEMPTS, _QUALITY_DIMS,
    _GREEN_THRESHOLD, _run_attempt, run_quality_search,
)
from app.services.library import build_scoring_style, list_library  # noqa: E402
from app.services.style_loader import list_styles, load_style     # noqa: E402

# ── sweep definition ──────────────────────────────────────────────────────────
SCHEMA_VERSION = 1
DEFAULT_OUT = REPO_ROOT / "docs" / "quality-baseline-v3.json"

# Every dimension score_generation returns, in report order. The first five are
# `_QUALITY_DIMS` — the ones the all-green gate actually tests.
DIMS = ("harmonic", "separation", "rhythm", "contour", "density", "mix",
        "style_match", "hook")

# `score_generation` reports these as 0.0 when they don't apply — style_match
# needs a mined corpus prior, hook needs a chorus — and leaves them out of the
# weighted total. Averaging those zeros in would report "style_match 0.54" for a
# sweep where every style that HAS a prior scored ~0.91, so aggregate them over
# the cases where they actually fired and show `--` when none did.
OPTIONAL_DIMS = ("style_match", "hook")

PARTS = ["chords", "bass", "melody", "drums"]

# Fixed seeds, generated by a Knuth LCG so the list is reproducible from code as
# well as from the stored file. Never renumber these: a baseline is only
# comparable to sweeps that used the same seeds.
def _seed_pool(n: int) -> list[int]:
    seeds, x = [], 20260804
    for _ in range(n):
        x = (x * 6364136223846793005 + 1442695040888963407) % (2 ** 62)
        seeds.append(x % (2 ** 31 - 1))
    return seeds


_SEEDS = _seed_pool(16)

# Styles the meter suite runs against — a spread of song-form, groove, and
# through-composed styles rather than all 35, since 10.2's question is whether
# non-4/4 scoring is sane, not which style wins.
METER_STYLES = ["rock", "jazz", "cinematic", "lofi", "funk", "epic_orchestral"]
METERS = ["3/4", "6/8", "7/8", "5/4"]

# A suite is one request shape swept across styles x seeds. `arrangement` is the
# primary sweep (all dimensions including hook, since a 16-bar arc plans a
# chorus); `loop_chorus` covers the app's default single-section path;
# `meters` feeds roadmap item 10.2.
SUITES: dict[str, dict] = {
    "arrangement": {
        "n_seeds": 16, "bars": 16, "complexity": 0.5, "variation": 0.4,
        "mode": "arrangement", "section_type": None, "meters": ["4/4"],
        "styles": "all",
    },
    "loop_chorus": {
        "n_seeds": 8, "bars": 8, "complexity": 0.6, "variation": 0.4,
        "mode": "loop", "section_type": "chorus", "meters": ["4/4"],
        "styles": "all",
    },
    "meters": {
        "n_seeds": 8, "bars": 16, "complexity": 0.5, "variation": 0.4,
        "mode": "arrangement", "section_type": None, "meters": METERS,
        "styles": METER_STYLES,
    },
}


# ── running ───────────────────────────────────────────────────────────────────

def _events_hash(all_events: dict) -> str:
    """Stable fingerprint of every generated note, for the byte-identical check."""
    h = hashlib.sha256()
    for part in sorted(all_events):
        h.update(f"[{part}]".encode())
        for e in all_events[part]:
            h.update(f"{e.pitch},{e.start:.6f},{e.duration:.6f},"
                     f"{e.velocity},{e.channel};".encode())
    return h.hexdigest()[:16]


def _prepare_style(style_id: str) -> tuple[dict, dict]:
    """Mirror /generate's style preparation so scores match the real endpoint."""
    style = load_style(style_id)
    style = _blend_styles(style, None, 0.5)
    style = {**style, "_humanize_scale": 0.5}
    return style, build_scoring_style(style, style_id)


def _run_case(style_id: str, style: dict, scoring_style: dict, scale: str,
              cfg: dict, meter: str, base_seed: int) -> dict:
    """Run one best-of-N search exactly as routes_generate._run_best_attempt does."""
    req = GenerateRequest(
        style_id=style_id, key="C", scale=scale, bars=cfg["bars"],
        time_signature=meter, complexity=cfg["complexity"],
        variation=cfg["variation"], parts=list(PARTS), mode=cfg["mode"],
        section_type=cfg["section_type"], seed=base_seed,
    )
    is_loop = cfg["mode"] == "loop"
    groove_push = style.get("groove_push", 0.0)
    sec_dom = style.get("secondary_dominants", False)
    tritone = style.get("tritone_substitution", False)

    # The production search itself (services.generation.run_quality_search), not a
    # copy of it — a re-implementation here could measure a search the app doesn't run.
    found = run_quality_search(
        lambda seed, **kw: _run_attempt(
            req, style, seed, is_loop, groove_push, sec_dom, tritone,
            scoring_style=scoring_style, **kw,
        ),
        base_seed,
    )
    best_q, best_events = found.quality, (found.result[0] if found.result else None)

    if best_q is None:
        return {"style": style_id, "seed": base_seed, "meter": meter, "error": True}

    return {
        "style": style_id,
        "seed": base_seed,
        "meter": meter,
        # Generation runs, so this stays comparable to the pre-11.4 baselines
        # (where one attempt was always exactly one run).
        "attempts": found.runs,
        "repairs": [r.describe() for r in found.repairs],
        "green": _all_green(best_q),
        "total": best_q["total"],
        "dims": {d: best_q.get(d, 0.0) for d in DIMS},
        "hash": _events_hash(best_events),
    }


def _cases(cfg: dict, style_metas: list[dict], seeds: list[int]):
    """Yield (style_meta, meter, seed) for one suite."""
    for meta in style_metas:
        for meter in cfg["meters"]:
            for seed in seeds[:cfg["n_seeds"]]:
                yield meta, meter, seed


def run_sweep(config: dict, only_suites: list[str] | None,
              only_styles: list[str] | None, quiet: bool) -> dict:
    all_meta = {m["id"]: m for m in list_styles()}
    suites_out: dict[str, list[dict]] = {}
    seeds = config["seeds"]
    t_start = time.perf_counter()

    for suite_name, cfg in config["suites"].items():
        if only_suites and suite_name not in only_suites:
            continue
        wanted = list(all_meta) if cfg["styles"] == "all" else list(cfg["styles"])
        if only_styles:
            wanted = [s for s in wanted if s in only_styles]
        metas = [all_meta[s] for s in wanted if s in all_meta]
        missing = [s for s in wanted if s not in all_meta]
        if missing:
            print(f"  [warn] {suite_name}: unknown styles {', '.join(missing)}")

        rows: list[dict] = []
        total = len(metas) * len(cfg["meters"]) * cfg["n_seeds"]
        t_suite = time.perf_counter()
        prepared: dict[str, tuple[dict, dict]] = {}

        for i, (meta, meter, seed) in enumerate(_cases(cfg, metas, seeds)):
            sid = meta["id"]
            if sid not in prepared:
                try:
                    prepared[sid] = _prepare_style(sid)
                except Exception as exc:                    # noqa: BLE001
                    print(f"  [warn] {sid}: load failed ({exc})")
                    prepared[sid] = None
            if prepared[sid] is None:
                continue
            style, scoring_style = prepared[sid]
            scale = meta.get("default_scale", "minor")
            try:
                rows.append(_run_case(sid, style, scoring_style, scale, cfg, meter, seed))
            except Exception as exc:                        # noqa: BLE001
                print(f"\n  [warn] {sid} seed={seed} meter={meter}: {exc}")
                rows.append({"style": sid, "seed": seed, "meter": meter, "error": True})

            if not quiet and (i % 20 == 0 or i + 1 == total):
                pct = (i + 1) / total * 100
                sys.stdout.write(f"\r  {suite_name:<14} [{pct:5.1f}%]  {i + 1}/{total}   ")
                sys.stdout.flush()

        if not quiet:
            dt = time.perf_counter() - t_suite
            sys.stdout.write(f"\r  {suite_name:<14} {len(rows)} cases in {dt:5.1f}s"
                             f"{' ' * 20}\n")
        suites_out[suite_name] = rows

    # Aggregates are stored alongside the raw cases so the file answers
    # "where are we today?" on its own — the raw rows exist for the per-case
    # hash check and for re-aggregating a subset.
    summary = {
        name: {"all": _agg(rows), "by_style": _by_style(rows)}
        for name, rows in suites_out.items()
    }

    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "git_commit": _git_commit(),
        "python": platform.python_version(),
        "green_threshold": _GREEN_THRESHOLD,
        "max_attempts": _MAX_QUALITY_ATTEMPTS,
        "green_dims": list(_QUALITY_DIMS),
        "library_fingerprint": _library_fingerprint(),
        "elapsed_s": round(time.perf_counter() - t_start, 1),
        "config": config,
        "summary": summary,
        "suites": suites_out,
    }


def _git_commit() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              cwd=REPO_ROOT, capture_output=True, text=True,
                              timeout=10).stdout.strip() or "unknown"
    except Exception:                                       # noqa: BLE001
        return "unknown"


def _library_fingerprint() -> dict:
    """Saved-generation counts per style.

    The scorer blends library-learned rhythm patterns into its style reference
    (`build_scoring_style`), so a library that grew between two sweeps moves
    scores on its own. Recording the counts makes that visible instead of
    silently poisoning a comparison.
    """
    counts: dict[str, int] = {}
    try:
        for entry in list_library():
            sid = entry.get("style_id", "?")
            counts[sid] = counts.get(sid, 0) + 1
    except Exception:                                       # noqa: BLE001
        return {}
    return dict(sorted(counts.items()))


# ── aggregation & reporting ───────────────────────────────────────────────────

def _agg(rows: list[dict]) -> dict:
    ok = [r for r in rows if not r.get("error")]
    if not ok:
        return {"n": 0}
    n = len(ok)

    def _dim_mean(d: str) -> float | None:
        vals = [r["dims"][d] for r in ok]
        if d in OPTIONAL_DIMS:
            vals = [v for v in vals if v > 0.0]
        return round(sum(vals) / len(vals), 4) if vals else None

    return {
        "n": n,
        "errors": len(rows) - n,
        "total": round(sum(r["total"] for r in ok) / n, 4),
        "green_rate": round(sum(1 for r in ok if r["green"]) / n, 4),
        "attempts": round(sum(r["attempts"] for r in ok) / n, 4),
        "dims": {d: _dim_mean(d) for d in DIMS},
        "dim_n": {d: sum(1 for r in ok if r["dims"][d] > 0.0) for d in OPTIONAL_DIMS},
    }


def _by_style(rows: list[dict]) -> dict[str, dict]:
    grouped: dict[str, list[dict]] = {}
    for r in rows:
        grouped.setdefault(r["style"], []).append(r)
    return {s: _agg(rs) for s, rs in sorted(grouped.items())}


def _c(value: float | None) -> str:
    """Traffic-light a 0-1 score. Same printable width (5) for every case, so the
    `:>17` column padding lines up despite the ANSI escapes."""
    if value is None:
        return "\033[90m   --\033[0m"
    color = ("\033[32m" if value >= _GREEN_THRESHOLD
             else "\033[33m" if value >= 0.52 else "\033[31m")
    return f"{color}{value:.3f}\033[0m"


def print_report(result: dict) -> None:
    for suite, rows in result["suites"].items():
        a = _agg(rows)
        if not a["n"]:
            print(f"\n  {suite}: no results")
            continue
        print(f"\n\033[1m  {suite.upper()} — {a['n']} cases  "
              f"total {a['total']:.3f}  green {a['green_rate'] * 100:.1f}%  "
              f"attempts {a['attempts']:.2f}\033[0m")
        hdr = f"  {'style':<18}{'total':>8}{'green':>8}{'att':>6}"
        for d in DIMS:
            hdr += f"{d[:6]:>8}"
        print(f"\033[90m{hdr}\033[0m")
        for sid, s in sorted(_by_style(rows).items(), key=lambda kv: kv[1].get("total", 0)):
            if not s["n"]:
                continue
            row = (f"  {sid:<18}{_c(s['total']):>17}"
                   f"{s['green_rate'] * 100:7.0f}%{s['attempts']:6.2f}")
            for d in DIMS:
                row += f"{_c(s['dims'][d]):>17}"
            print(row)
        print(f"  \033[1m{'ALL':<18}{_c(a['total']):>17}"
              f"{a['green_rate'] * 100:7.0f}%{a['attempts']:6.2f}"
              + "".join(f"{_c(a['dims'][d]):>17}" for d in DIMS) + "\033[0m")


def _dim_row(label: str, before: dict, after: dict) -> str:
    row = f"  {label:<18}"
    for key in ("total", "green_rate", "attempts"):
        d = after[key] - before[key]
        mark = "\033[32m" if (d > 0) == (key != "attempts") and abs(d) > 1e-4 else (
               "\033[31m" if abs(d) > 1e-4 else "\033[90m")
        row += f"{mark}{d:+8.3f}\033[0m"
    for d in DIMS:
        b, a = before["dims"][d], after["dims"][d]
        if b is None or a is None:
            row += "\033[90m      --\033[0m"
            continue
        delta = a - b
        mark = ("\033[32m" if delta > 1e-4 else
                "\033[31m" if delta < -1e-4 else "\033[90m")
        row += f"{mark}{delta:+8.3f}\033[0m"
    return row


def print_comparison(base: dict, new: dict) -> int:
    """Print baseline-vs-now deltas. Returns the number of changed event hashes."""
    print(f"\n\033[1m  COMPARISON  baseline {base.get('git_commit')} "
          f"({base.get('generated_at')})  ->  now {new.get('git_commit')}\033[0m")
    if base.get("library_fingerprint") != new.get("library_fingerprint"):
        print("  \033[33m[warn] library contents changed since the baseline — "
              "learned scoring patterns differ, so deltas are not purely code.\033[0m")

    changed_total = 0
    for suite, new_rows in new["suites"].items():
        base_rows = base["suites"].get(suite)
        if not base_rows:
            print(f"\n  {suite}: not in baseline, skipping")
            continue
        b_index = {(r["style"], r["seed"], r["meter"]): r for r in base_rows}
        matched = [(b_index[k], r) for r in new_rows
                   if (k := (r["style"], r["seed"], r["meter"])) in b_index
                   and not r.get("error") and not b_index[k].get("error")]
        if not matched:
            print(f"\n  {suite}: no comparable cases")
            continue

        b_agg, n_agg = _agg([m[0] for m in matched]), _agg([m[1] for m in matched])
        changed = [(b, n) for b, n in matched if b["hash"] != n["hash"]]
        changed_total += len(changed)

        print(f"\n\033[1m  {suite.upper()} — {len(matched)} comparable cases, "
              f"{len(changed)} with changed events\033[0m")
        hdr = f"  {'':<18}{'total':>8}{'green':>8}{'att':>8}"
        for d in DIMS:
            hdr += f"{d[:6]:>8}"
        print(f"\033[90m{hdr}\033[0m")
        print(_dim_row("ALL (delta)", b_agg, n_agg))

        # The styles that moved most, either way — where to point the ears.
        b_styles, n_styles = _by_style([m[0] for m in matched]), _by_style([m[1] for m in matched])
        movers = sorted(
            ((s, n_styles[s]["total"] - b_styles[s]["total"]) for s in n_styles if b_styles[s]["n"]),
            key=lambda kv: -abs(kv[1]),
        )[:6]
        if movers and abs(movers[0][1]) > 1e-4:
            parts = ["\033[32m" + s + f" {d:+.3f}\033[0m" if d > 0
                     else "\033[31m" + s + f" {d:+.3f}\033[0m"
                     for s, d in movers if abs(d) > 1e-4]
            print("  \033[90mbiggest movers:\033[0m " + "  ".join(parts))

    tint = "\033[33m" if changed_total else "\033[32m"
    print(f"\n  Event hashes changed: {tint}{changed_total}\033[0m\n")
    return changed_total


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help=f"where to write the sweep (default {DEFAULT_OUT.relative_to(REPO_ROOT)})")
    ap.add_argument("--compare", type=Path, default=None,
                    help="compare against this baseline instead of writing one")
    ap.add_argument("--suites", nargs="*", default=None, choices=list(SUITES),
                    help="only run these suites")
    ap.add_argument("--styles", nargs="*", default=None, help="only run these styles")
    ap.add_argument("--require-identical", action="store_true",
                    help="with --compare, exit 1 if any event hash changed")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    base = None
    if args.compare:
        if not args.compare.exists():
            print(f"Baseline not found: {args.compare}")
            return 2
        base = json.loads(args.compare.read_text())
        config = base["config"]            # replay the baseline's own config
    else:
        config = {"seeds": _SEEDS, "suites": SUITES}

    n_styles = len(list_styles())
    print(f"\n\033[1m  GenreGrid quality baseline\033[0m  "
          f"({n_styles} styles, green >= {_GREEN_THRESHOLD}, "
          f"best-of-{_MAX_QUALITY_ATTEMPTS})\n")

    result = run_sweep(config, args.suites, args.styles, args.quiet)

    if base:
        changed = print_comparison(base, result)
        if args.out != DEFAULT_OUT:
            args.out.write_text(json.dumps(result, indent=1))
            print(f"  Wrote {args.out}")
        return 1 if (args.require_identical and changed) else 0

    print_report(result)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, indent=1))
    print(f"\n  Wrote \033[1m{args.out}\033[0m "
          f"({args.out.stat().st_size / 1024:.0f} KB, {result['elapsed_s']}s)\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
